#!/bin/bash
exec scala "$0" "$@"
!#

import sys.process._
import scala.language.postfixOps

object ListFiles {
	def main(args: Array[String]) {		
    	val files = ("ls ." !!).split("\n")
    	files.foreach {
    		println _ 
    	}
  	}
}

ListFiles.main(args)